services:

  api:
    build: api/
    # do not publish any ports, will be reverse-proxied by nginx
    expose:
      - 3000
    environment:
      NODE_ENV: production
      PORT: 3000
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}

    
  ui:
    # do not publish any ports, will be reverse-proxied by nginx
    expose:
      - 80
    environment:
      NODE_ENV: production

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates/nginx.conf:/etc/nginx/templates/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}
    depends_on:
      - api
      - ui
  
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL_ADMIN} -d ${DOMAIN} --agree-tos
    depends_on:
      - nginx