services:

  api:
    build: api/
    # do not publish any ports, will be reverse-proxied by nginx-https
    expose:
      - 3000
    environment:
      NODE_ENV: production
      PORT: 3000
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}

    
  ui:
    # do not publish any ports, will be reverse-proxied by nginx-https
    expose:
      - 80
    environment:
      NODE_ENV: production

  nginx-https:
    container_name: nginx-https
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - ui
  
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email leo.hilsheimer@gmail.com -d ${DOMAIN} --agree-tos