version: '3'

services:

  api:
    restart: always
    # do not publish any ports, will be reverse-proxied
    expose:
      - 3000
    networks:
      - net
      - default
    volumes:
      - media:/media
    env_file: .env
    build:
      args:
        PAYLOAD_PUBLIC_HOST_UI: https://${DOMAIN_UI}
        PAYLOAD_PUBLIC_HOST_API: https://${DOMAIN_API}
        MEDIA_DIR: /media
    environment:
      NODE_ENV:
      MEDIA_DIR: /media
      PAYLOAD_PUBLIC_HOST_UI: https://${DOMAIN_UI}
      PAYLOAD_PUBLIC_HOST_API: https://${DOMAIN_API}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      EMAIL_FROM_ADDRESS:
      EMAIL_FROM_NAME:
      SMTP_HOST:
      SMTP_PORT:
      SMTP_USER:
      SMTP_PASS:
      VIRTUAL_HOST: ${DOMAIN_API}
      LETSENCRYPT_HOST: ${DOMAIN_API}
      LETSENCRYPT_EMAIL: ${EMAIL_ADMIN}
      MONGODB_URI: mongodb://mongo:27017/payload_prod
    
  mongo:
    restart: always
    volumes:
      - data:/data/db
    expose:
      - 27017
    
  ui:
    restart: always
    # do not publish any ports, will be reverse-proxied
    expose:
      - 80
    networks:
      - net
      - default
    env_file:
      - .env
    build:
      args:
        VITE_HOST_API: https://${DOMAIN_API}
    environment:
      NODE_ENV:
      VITE_HOST_API: https://${DOMAIN_API}
      VIRTUAL_HOST: ${DOMAIN_UI}
      LETSENCRYPT_HOST: ${DOMAIN_UI}
      LETSENCRYPT_EMAIL: ${EMAIL_ADMIN}

  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:latest # alpine?
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks: 
      - net
    ports:
      - "80:80"
      - "443:443"
  
  certbot:
    image: nginxproxy/acme-companion
    container_name: certbot
    volumes_from:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: ${EMAIL_ADMIN}
      # ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory # staging
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  media:
  data:
  certs:
  html:
  vhost:
  dhparam:
  acme:

networks:
  net:
    name: net
    external: true