services:
  app:
    image: node:18-alpine
    ports:
      - 80:3000
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    working_dir: /home/node/app/
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      PAYLOAD_PUBLIC_SERVER_URL: http://${HOSTNAME}
      NEXT_PUBLIC_SERVER_URL: http://${HOSTNAME}
      NEXTAUTH_URL: http://${HOSTNAME}
      MONGO_URL: mongodb://db:27017/app

  db:
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump  # for restoring db dumps
      - data:/data/db
  
volumes:
  data: