version: '3.8'

services:
  app:
    build:
      context: ./
      target: runner
      args:
        PAYLOAD_PUBLIC_SERVER_URL: http://${HOSTNAME}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
        MONGO_URL: ${MONGO_URL}
    ports:
      - 80:3000
    volumes:
      - media:/app/media
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://db:27017/app
      PAYLOAD_CONFIG_PATH: /app/dist/payload.config.js
      PAYLOAD_PUBLIC_SERVER_URL: http://${HOSTNAME}
      NEXT_PUBLIC_SERVER_URL: http://${HOSTNAME}
      NEXTAUTH_URL: http://${HOSTNAME}
      HOSTNAME:
      PAYLOAD_SECRET:
      NEXTAUTH_SECRET:
    restart: unless-stopped

  db:
    image: mongo:4.4.18 # last version running without CPU flag AVX
    expose:
      - 27017
    volumes:
      - ./dump:/dump  # for restoring db dumps
      - data:/data/db
    restart: unless-stopped
  
volumes:
  data:
  media:
