services:

  api:
    # publish api on port 3000
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING

  ui:
    # publish ui on port 8080
    ports:
      - "8080:80"
    environment:
      NODE_ENV: development