services:

  ui:
    container_name: ui
    build:
      context: ui/

  api:
    container_name: api
    build:
      context: api/
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: none
