version: '3.8'

services:
  frontend:
    image: node:18-alpine
    build:
      network: host
    ports:
      - 80:3000
    expose:
      - 3000
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    extra_hosts:
      - ${HOSTNAME_BACKEND}:172.17.0.1  # hack that allows frontend to get backend routes by the public URL
    environment:
      HOSTNAME:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_SERVER_URL: http://${HOSTNAME}
      NEXTAUTH_SECRET: secret123
      NEXTAUTH_URL: http://${HOSTNAME}

      TIMEZONE: Europe/Berlin

      DOMAIN_BACKEND: ${HOSTNAME_BACKEND}
      NEXT_PUBLIC_HOST_BACKEND: http://${HOSTNAME_BACKEND}:3000
      INTERNAL_HOST_BACKEND: http://backend:3000  # works from one docker container to another

      REVALIDATION_SECRET: secret123

  backend:
    image: node:18-alpine
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app/
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    environment:
      HOSTNAME:
      NODE_ENV: development
      PAYLOAD_PUBLIC_SERVER_URL: http://${HOSTNAME_BACKEND}:3000
      MONGODB_URI: mongodb://db:27017/app
      PAYLOAD_SECRET: secret123

      FRONTEND_HOST: http://frontend:3000
      REVALIDATION_SECRET: secret123

  db:
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump  # for restoring db dumps
      - data:/data/db
  
volumes:
  data:
