services:

  ui:
    container_name: ui
    build:
      context: ui/

  api:
    container_name: api
    build:
      context: api/
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: none
