services:

  api:
    # do not publish any ports, will be reverse-proxied
    expose:
      - 3000
    networks:
      - net
      - default
    env_file:
      - .env
    environment:
      - NODE_ENV
      - DOMAIN_UI
      - DOMAIN_API
      - PAYLOAD_PUBLIC_DOMAIN_API=${DOMAIN_API}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - VIRTUAL_HOST=${DOMAIN_API}
      - LETSENCRYPT_HOST=${DOMAIN_API}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - MONGODB_URI=mongodb://mongo:27017/payload_prod
    
  mongo:
    expose:
      - 27017
    
  ui:
    # do not publish any ports, will be reverse-proxied
    expose:
      - 80
    networks:
      - net
      - default
    env_file:
      - .env
    environment:
      - NODE_ENV
      - VITE_DOMAIN_API=${DOMAIN_API}
      - VIRTUAL_HOST=${DOMAIN_UI}
      - LETSENCRYPT_HOST=${DOMAIN_UI}
      - LETSENCRYPT_EMAIL=${EMAIL}

  proxy:
    container_name: "proxy"
    image: "jwilder/nginx-proxy:latest" # alpine?
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "net"
    ports:
        - "80:80"
        - "443:443"
  
  letsencrypt:
    container_name: "letsencrypt"
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        NGINX_PROXY_CONTAINER: "proxy"
        DEFAULT_EMAIL: ${EMAIL}
    restart: "always"
    depends_on:
        - "proxy"
    networks: 
        - "net"

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  net: