services:

  ui:
    container_name: ui
    build: ./ui

  api:
    container_name: api
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
