version: '3.8'

services:
  frontend:
    container_name: frontend
    depends_on:
      - backend

  backend:
    container_name: backend
    depends_on:
      - db
  
  db:
    container_name: db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger