services:
  app:
    build:
      context: ./
      target: runner
      args:
        MONGO_URL: mongodb://db:27017/app 
    ports:
      - 80:3000
    volumes:
      - media:/app/media
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://db:27017/app
    restart: always

  db:
    image: mongo:4.4.18 # last version running without CPU flag AVX
    expose:
      - 27017
    volumes:
      - ./dump:/dump  # for restoring db dumps
      - data:/data/db
    restart: always
  
volumes:
  data:
  media: