services:
  frontend:
    container_name: frontend

  backend:
    container_name: backend
    depends_on:
      - db
  
  db:
    container_name: db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger