services:
  frontend:
    image: node:18-alpine
    ports:
      - 80:3000
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_SERVER_URL: http://${HOSTNAME}
      NEXTAUTH_URL: http://${HOSTNAME}
      GRAPHQL_LOCALHOST: http://backend:3000/api/graphql  # works from one docker container to another
      NEXT_PUBLIC_MEDIA_URL: http://${HOSTNAME}:3000/media  # works in public internet

  backend:
    image: node:18-alpine
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app/
    command: sh -c "yarn && yarn dev"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PAYLOAD_PUBLIC_SERVER_URL: http://${HOSTNAME}:3000
      MONGODB_URI: mongodb://db:27017/app

  db:
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump  # for restoring db dumps
      - data:/data/db
  
volumes:
  data: